package App::CpanInteg;
use strict;
use warnings;

use HTTP::Tiny;
use JSON::PP ();
use Digest::SHA qw(sha256_hex);

our $VERSION = '0.001';

my $API = 'https://fastapi.metacpan.org/v1';

sub _ua { HTTP::Tiny->new(agent => "cpan-integ/$VERSION ", timeout => 30) }

sub run {
    my ($class, @argv) = @_;
    my $cmd = shift @argv;
    $cmd = 'help' unless defined $cmd;

    return cmd_pin(@argv)    if $cmd eq 'pin';
    return cmd_verify(@argv) if $cmd eq 'verify';
    return cmd_help()        if $cmd eq 'help' || $cmd eq '--help' || $cmd eq '-h';

    warn "cpan-integ: unknown command '$cmd'\n\n";
    cmd_help();
    return 2;
}

sub cmd_help {
    print <<"USAGE";
cpan-integ $VERSION — consumer-side install-time integrity for CPAN

Records an expected SHA-256 per resolved distribution, then fails the build
if a fetched artifact does not match. Trust model: trust-on-first-pin
(MetaCPAN's per-release checksum), cryptographically verified thereafter.

Usage:
  cpan-integ pin    [--snapshot cpanfile.snapshot] [--out cpanfile.integrity]
  cpan-integ verify [--integrity cpanfile.integrity]

  pin     Resolve each distribution in a cpanfile.snapshot to its MetaCPAN
          SHA-256 and write a PURL -> sha256 lockfile.
  verify  Re-fetch each pinned artifact and fail if its SHA-256 differs.
USAGE
    return 0;
}

# --argv parsing: turns ("--snapshot", "x", "--out", "y") into a hash,
# layered over the supplied defaults.
sub _parse_argv {
    my ($defaults, @argv) = @_;
    my %o = %$defaults;
    while (@argv) {
        my $a = shift @argv;
        if ($a =~ /^--(\w+)$/) { $o{$1} = shift @argv }
        else { die "cpan-integ: unexpected argument '$a'\n" }
    }
    return %o;
}

sub cmd_pin {
    my %o = _parse_argv({ snapshot => 'cpanfile.snapshot', out => 'cpanfile.integrity' }, @_);

    -e $o{snapshot} or die "cpan-integ: snapshot not found: $o{snapshot}\n";
    my @paths = _parse_snapshot($o{snapshot});
    @paths or die "cpan-integ: no distributions found in $o{snapshot}\n";

    my $ua = _ua();
    open my $fh, '>', $o{out} or die "cpan-integ: cannot write $o{out}: $!\n";
    print {$fh} "# cpanfile.integrity — generated by cpan-integ $VERSION\n";
    print {$fh} "# format: <purl> sha256:<hex> <download_url>\n";

    my $pinned = 0;
    for my $path (@paths) {
        my ($author, $name) = _author_release($path);
        my $rel = _release_meta($ua, $author, $name);
        unless ($rel && $rel->{checksum_sha256}) {
            warn "cpan-integ: no MetaCPAN checksum for $path (skipped)\n";
            next;
        }
        my $purl = sprintf 'pkg:cpan/%s/%s@%s',
            uc($rel->{author}), $rel->{distribution}, $rel->{version};
        printf {$fh} "%s sha256:%s %s\n",
            $purl, $rel->{checksum_sha256}, $rel->{download_url};
        warn "  pinned $purl\n";
        $pinned++;
    }
    close $fh;
    print "cpan-integ: pinned $pinned distribution(s) to $o{out}\n";
    return 0;
}

sub cmd_verify {
    my %o = _parse_argv({ integrity => 'cpanfile.integrity' }, @_);

    -e $o{integrity} or die "cpan-integ: integrity file not found: $o{integrity}\n";
    open my $fh, '<', $o{integrity} or die "cpan-integ: cannot read $o{integrity}: $!\n";

    my $ua = _ua();
    my ($ok, $fail, $total) = (0, 0, 0);
    while (my $line = <$fh>) {
        next if $line =~ /^\s*#/ || $line =~ /^\s*$/;
        my ($purl, $sha, $url) = split ' ', $line;
        next unless $purl && $sha && $url;
        $sha =~ s/^sha256://;
        $total++;

        my $res = $ua->get($url);
        unless ($res->{success}) {
            printf "FAIL  %s  (download error: %s %s)\n", $purl, $res->{status}, $res->{reason};
            $fail++;
            next;
        }
        my $got = lc sha256_hex($res->{content});
        if ($got eq lc $sha) {
            printf "ok    %s\n", $purl;
            $ok++;
        }
        else {
            printf "FAIL  %s\n        expected %s\n        got      %s\n", $purl, lc($sha), $got;
            $fail++;
        }
    }
    close $fh;
    printf "\ncpan-integ: %d verified, %d failed, %d total\n", $ok, $fail, $total;
    return $fail ? 1 : 0;
}

# A cpanfile.snapshot records each distribution's tarball under a "pathname:"
# line, e.g. "    pathname: E/ET/ETHER/Try-Tiny-0.32.tar.gz".
sub _parse_snapshot {
    my ($file) = @_;
    open my $fh, '<', $file or die "cpan-integ: cannot read $file: $!\n";
    my @paths;
    while (my $line = <$fh>) {
        push @paths, $1 if $line =~ /^\s*pathname:\s*(\S+)/;
    }
    close $fh;
    return @paths;
}

# "E/ET/ETHER/Try-Tiny-0.32.tar.gz" -> ("ETHER", "Try-Tiny-0.32")
sub _author_release {
    my ($path) = @_;
    my @seg    = split m{/}, $path;
    my $author = $seg[-2];
    (my $name = $seg[-1]) =~ s/\.(?:tar\.gz|tar\.bz2|tgz|zip)$//;
    return ($author, $name);
}

# The /release/{author}/{name} endpoint wraps the object in a "release" key;
# /release/{dist} returns it bare. Unwrap either shape.
sub _release_meta {
    my ($ua, $author, $name) = @_;
    my $res = $ua->get("$API/release/$author/$name");
    return undef unless $res->{success};
    my $data = eval { JSON::PP->new->decode($res->{content}) };
    return undef unless $data;
    my $rel = $data->{release} || $data;
    return ref $rel eq 'HASH' && $rel->{checksum_sha256} ? $rel : undef;
}

1;
